# Generated by Django 2.0.9 on 2018-11-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ciudadPersona',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='regionPersona',
            field=models.CharField(max_length=100),
        ),
    ]
