# Generated by Django 2.1.3 on 2018-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_auto_20181108_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='Sistema/static/media/img_perros/noname.jpg', upload_to='Sistema/static/media/img_perros'),
        ),
    ]
