# Generated by Django 2.0.9 on 2018-11-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_auto_20181108_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotapersona',
            name='codigoMascota',
        ),
        migrations.RemoveField(
            model_name='mascotapersona',
            name='codigoPersona',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='descripcionMascotra',
            new_name='descripcion',
        ),
        migrations.DeleteModel(
            name='MascotaPersona',
        ),
    ]
