# Generated by Django 2.1.3 on 2018-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_auto_20181108_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estadoMascota',
            field=models.CharField(default='Rescatado', max_length=50),
        ),
    ]
