# Generated by Django 2.1.3 on 2018-11-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_auto_20181108_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='user',
            new_name='usuario',
        ),
    ]
